FROM m1k1o/neko:firefox

COPY supervisord.conf /etc/neko/supervisord/code.conf
COPY firefox/policies.json /usr/lib/firefox/distribution/policies.json
COPY firefox/neko.js /usr/lib/firefox/mozilla.cfg
