##################################
## CODX-ROOM CUSTOM IMAGE
##
## Added aws and s3 sync with r
##################################
FROM codx/room:latest

ENV AWS_CLIENT_ID=
ENV AWS_CLIENT_SECRET=
ENV AWS_S3_BUCKET=

# rclone
RUN curl https://rclone.org/install.sh | sudo bash


# AWS